version: '2'

  services:
  backend:
    build: backend
    image: debian
    ports:
      - 9000:9000
    volumes:
     - .:/code
  
  frontend:
    build: frontend
    image: debian
    volumes:
     - .:/code