version: '2'

services:
   backend:
      build: backend
      image: node
      ports:
      - "9000:9000"  
      volumes:
      - .:/code
      tty: true
  
   frontend:
      build: frontend
      image: node
      ports:
      - "8000:8000"
      volumes:
      - .:/code
      tty: true
      links:
      - backend