version: '2'

services:
  backend:
    build: backend
    environment:
      APPID: 7093bd26ea2ca1f8800f9af6f7597134
    ports:
    - 9000:9000

  frontend:
    build: frontend
    ports:
    - 8000:8000
